[package]
name = "statisticalme"
version = "20.3.6"
authors = ["Antony <dentad@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "statisticalme"
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true

[dependencies]

[dependencies.pyo3]
version = "0.11"
features = ["extension-module"]
