[package]
name = "statisticalme"
version = "22.0.0"
authors = ["Antony <dentad@users.noreply.github.com>"]
edition = "2021"

[lib]
name = "statisticalme"
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
debug = false
lto = true

[dependencies]
pyo3 = { version = "0.16", features = ["extension-module"] }
chrono = "0.4"
chrono-tz = "0.6"
unicase = "2.6"
