[package]
name = "statisticalme"
version = "21.0.0"
authors = ["Antony <dentad@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "statisticalme"
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true

[dependencies]
pyo3 = { version = "0.13", features = ["extension-module"] }
chrono = "0.4"
