[package]
name = "statisticalme"
version = "22.0.0"
authors = ["Antony <dentad@users.noreply.github.com>"]
edition = "2018"

[lib]
name = "statisticalme"
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true

[dependencies]
pyo3 = { version = "0.16", features = ["extension-module"] }
chrono = "0.4"
chrono-tz = "0.6"
unicase = "2.6"
psutil = { version = "3.2", default-features = false, features = ["cpu", "process"] }
# lazy_static = "1.4"
